spring:
  profiles:
    include: native
  application:
    name: settingApiManager
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configs/,classpath:configs/{application}
server:
  port: 8086
